// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"rpc/internal/logic"
	"rpc/internal/svc"
	"rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// Login 用户登录
func (s *UserServer) Login(ctx context.Context, in *user.ULoginRequest) (*user.ULoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

// Register 用户注册
func (s *UserServer) Register(ctx context.Context, in *user.URegisterRequest) (*user.URegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

// GetUserInfo 获取用户信息
func (s *UserServer) GetUserInfo(ctx context.Context, in *user.UInfoRequest) (*user.UInfoResponse, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}
